### ISSUE TITLE
There is a way to remove the fixer  on click?

### ISSUE THREAD

**Issue by ImaRamos** [lai32290/TableHeadFixer#21]
Hello Friends,

I need to remove the fixer on click, somebody can help me please?
Thanks.

Best Regards

**Comment by lai32290** [comment]
Actual has not dispose any function or event to handle this situation.

But maybe you can add Click event to cell where your want handle, you can just remove `display: relative` in cell css, maybe is work for you

**Comment by lai32290** [comment]
Actual has not dispose any function or event to handle this situation.

But maybe you can add Click event to cell where your want handle, you can just remove display: relative in cell css, maybe is work for you

**Comment by lai32290** [comment]
I really really Sorry, I miss click and close this issue
