### ISSUE TITLE
Fixed cells while content changed with AJAX

### ISSUE THREAD

**Issue by scion4581** [lai32290/TableHeadFixer#34]
How to make this plugin work with dynamically added cells?

**Comment by lai32290** [comment]
This plugin will not add any row or column to your table, just fix it, so maybe you can call the plugin function one more time, after you add the new content to the table with your way

**Comment by scion4581** [comment]
Hi. Yeah, I am caliing tableHeadFixer on table after change content  and all works fine, thanks
