### ISSUE TITLE
ReferenceError: setParent is not defined in Firefox 38.0.1

### ISSUE THREAD

**Issue by talklikethat** [lai32290/TableHeadFixer#38]
Hello.
In Firefox 38.0.1 i see ReferenceError: setParent is not defined 

jQuery 3.2.1 + last version jquery-table-fixer (from npm)
https://jsfiddle.net/q7t0z98p/1/

**Comment by lai32290** [comment]
I'll take a look at it, thanks for feedback

**Comment by lai32290** [comment]
I updated it, please download the new version and try again.

**Comment by talklikethat** [comment]
All ok. 
Thx!
