### ISSUE TITLE
table width is being compressed in Safari

### ISSUE THREAD

**Issue by market-fresh** [lai32290/TableHeadFixer#40]
It seems like the table width is being ignored in Safari. The table jets compressed to fit all the columns into the screen rather than being allowed to scroll through with fixed left column and fixed header.

**Comment by lai32290** [comment]
hey @market-fresh , thanks for your feedback, actually I've never test it on Safari, I should say sorry about it.
I'll take a look at it later.

**Comment by market-fresh** [comment]
hi lai. i am reporting the issue with Safari. but i'd also like to add then whenever i view the table in an ipad or iphone (any browser) the table gets compressed. the only css i use is the default bootstrap.

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

not sure why the behaviour is this way for the table when accessed via an ipad or iphone.

**Comment by market-fresh** [comment]
hi lai. i found the problem with my issue. the css examples i found online added the line "table-layout:fixed" which does not seem to impact on Chrome but somehow compresses the table in Safari and Firefox. I have removed that line in my css. 

i am closing this issue. thanks!

**Comment by lai32290** [comment]
@market-fresh Cool!! thanks for the answer!!!
