### ISSUE TITLE
Want hover effect on fixed column

### ISSUE THREAD

**Issue by thaw-frobom** [lai32290/TableHeadFixer#41]
When I mouseover the one row, the entire row doesn't fire hover effect. Only the unfixed column change color and the fixed columns doesn't change background color. Because the background doesn't change in fixed columns.
Can you implement to add this function?

**Comment by lai32290** [comment]
Weird, seems working as I tested, could you show me how do you doing please?
You can execute this code in `examples/fixHeader.html`

```
$("#fixTable thead th").hover(() => {
   console.log("Hover");
});
```

**Comment by thaw-frobom** [comment]
Thanks for your reply. My problem is I use `https://github.com/puikinsh/gentelella` template and I use jambo_table table class to add hover effect(which change row color). But the hover effect doesn't work on fixed column. Is there any solution for that. Or may I write own javascript to change fixed-column background when hover.

**Comment by lai32290** [comment]
I don't know about this template, but in the case, you just wanna change background color, you can just add a class for `thead tr` and creating the effect using CSS selector like:
```
thead tr > *:hover {
    background-color: green;
}
```

**Comment by thaw-frobom** [comment]
Thanks you. I found a solution for that. I modify your code a little because when you fixed one of the left column your hover doesn't effect on the fixed cell. I added `!important` in `background-color`.

**Comment by lai32290** [comment]
Great! thanks for your feedback!
