### ISSUE TITLE
Table borders being ignored

### ISSUE THREAD

**Issue by robinpoort** [lai32290/TableHeadFixer#5]
Both bottom and top borders are being ignored on sticky headers and footers.

See: http://www.jqueryscript.net/demo/jQuery-Plugin-For-Fixed-Table-Header-Footer-Columns-TableHeadFixer/examples/fixHeader.html

It would be nice if border styling would be respected once you've scrolled.

![table-headers-border](https://cloud.githubusercontent.com/assets/4848082/8697283/0a8356c0-2af4-11e5-8bc9-aa1144f6b3c0.gif)

**Comment by lai32290** [comment]
Thank you very much! I'll fix this problem as soon as possible

**Comment by lai32290** [comment]
I checked this problem is because the style of table, is set `border-collapse: collapse`, if you set it in `border-collapse: separate`, will not occur this problem

**Comment by niciliketo** [comment]
The comments here say `border-collapse`, but the README.md says `table-collapse`.

I think `table-collapse` is incorrect as it is not a css property.

**Comment by robinpoort** [comment]
Should indeed be `border-collapse: separate` and confirmed that it fixes the problem.
