### ISSUE TITLE
Couldnt fix table with rowspan in first column

### ISSUE THREAD

**Issue by niciliketo** [lai32290/TableHeadFixer#7]
Hi I couldn't correctly fix the first column of a table with this format:
`````
<table>
  <tr>
    <td rowspan=2>title</td>
    <td> content</td>
  </tr>
  <tr>
    <td>content 2</td>
  </tr>
  <tr>
    <td>title2</td>
    <td>content3</td>
  </tr>
</table>
`````
I want the first column to fix, but in row 2, the 2nd column is fixed (because this row does not have its own col1).

**Comment by niciliketo** [comment]
https://github.com/lai32290/TableHeadFixer/pull/8 is my attempt at fixing it, but not sure if this is the best way

**Comment by lai32290** [comment]
Great! I will fix this problem
